# Generated by Django 5.0.6 on 2024-06-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='rate',
        ),
    ]
