# Generated by Django 5.0.6 on 2024-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_product_pro_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='include_tax',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
