# Generated by Django 5.0.6 on 2024-07-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_bill_include_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_pic',
        ),
    ]
