# Generated by Django 5.0.6 on 2024-07-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_remove_product_pro_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='huid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
